
environment:
  VSCODE_BUILD_VERBOSE: true

version: 0.0.{build}

install:
  - ps: Install-Product node 7.8.0 x64
  - npm install -g npm vsce > log.txt
  - npm install >> log.txt

cache:
  - node_modules

build_script:
  - npm version "{version}"
  - npm run package

test_script:
  - node --version
  - npm --version
  - npm install -g mocha appveyor-mocha
  - npm test

artifacts:
  - path: '**\*.vsix'

  - path: 'log.txt'
    name: build logs
