install:
  - ps: Install-Product node 6.5 x64

build_script:
  - npm install
  - ps: vsce package

test_script:
  - npm install appveyor-mocha
  - npm test

artifacts:
  - path: '*.vsix'
    name: vscode-atmel-debug
