
environment:
  VSCODE_BUILD_VERBOSE: true
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "7"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm vsce > log.txt
  - npm install >> log.txt

cache:
  - node_modules

build_script:
  - ps: npm version "$env:APPVEYOR_BUILD_VERSION"
  - npm run package

test_script:
  - node --version
  - npm --version
  - npm test

artifacts:
  - path: '**\*.vsix'

  - path: 'log.txt'
    name: build logs
