install:
  - ps: Install-Product node 6.5 x64
  - node --version
  - npm --version
  - npm install

build_script:
  - cmd: "vsce package"

test_script:
  - npm install appveyor-mocha
  - npm test

artifacts:
  - path: '*.vsix'
    name: vscode-atmel-debug
